# Generated by Django 4.0.3 on 2022-03-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_brand_description_brand_qr_code_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
