# Generated by Django 4.0.3 on 2022-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
