# Generated by Django 4.0.3 on 2022-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_brand_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
