# Generated by Django 4.0.3 on 2022-04-13 17:41

import apps.base.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_brand_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.base.helpers.custom_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
