# Generated by Django 4.0.3 on 2022-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_Active',
            field=models.BooleanField(default=False),
        ),
    ]
