# Generated by Django 4.0.3 on 2022-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_Active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
