# Generated by Django 4.0.3 on 2022-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_rename_is_active_menu_is_active_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
