# Generated by Django 3.2.13 on 2022-04-16 14:12

import apps.base.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.base.helpers.custom_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
