# Generated by Django 4.0.4 on 2022-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_menudetail_order_alter_menu_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetail',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
