# Generated by Django 4.0.4 on 2022-04-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_alter_menudetail_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menudetail',
            options={'ordering': ['order']},
        ),
    ]
