# Generated by Django 4.0.4 on 2022-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_alter_menudetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetail',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
