# Generated by Django 4.0.4 on 2022-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_alter_menudetail_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_product_name'),
        ),
    ]
